### ISSUE TITLE
Species taxonomy

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#23]
The species taxonomy probably needs to be updated as I have encountered species in the Icelandic stomach data base that are not described in mfdb::species. We have been digging into species taxonomy at the MRI, and we have discovered that the current mfdb::species table originates from NOAA, i.e. the NODC taxonomy:

> http://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.nodc:50418

which since has been updated and revised from when it was used as the dst^2 species taxonomy, on which mfdb species table is based. The Americans have actually defined a whole new taxonomy since then, the TSN taxonomy:

> http://www.itis.gov/

which is mainly used in the Americas and there is a one-to-one link from NODC to TSN. Now to add to the confusion people on the other side of the Atlantic decided to use a different taxonomy registry, namely WoRMS:

> http://www.marinespecies.org/

But ICES at least provides TSN and WoRMS ids at their website so there may be a possibility to link the two. 

So I would like to suggest in the short term it to update the mfdb::species with the most up to date NODC but in the long term we may want to align the species definitions to either TSN or WoRMS.

**Comment by lentinj** [comment]
You're right, NODC must be the taxonomy it's based on. However, the 3 letter abbreviations we use don't appear to be part of the taxonomy. I don't think it's worth spending ages finding a source for these for every species, but If there's some in particular you want, then we can just add them in today.

https://www.nodc.noaa.gov/access/dataformats.html suggests that both ITIS and NODC are unmaintained, and if WoRMS is what's used this side of the Atlantic anyway then it would make a lot more sense.

Instead of maintaining our own subset of WoRMS (which I'm not sure would be necessarily superior to poking extra entries in the NODC vocab), it'd make more sense to integrate with the WoRMS webservice, so before importing data you could do something like:

```
mfdb_download_species(mdb, list(COD="gadus morhua", HKE="Merluccius Merluccius"))
```

The advantage of this is you can use your data's abbreviations rather than having a translation layer (at the size of WoRMS, a 3-letter code would be impossible anyway), and you wouldn't be dependent on MFDB releases to add extra species. It'd also be possible without having to write to them to obtain a database dump, they may not be best pleased if our reasons why is so we can go publish it on Github :)

The API shoud be able to give us loose matches as you've asked for before, e.g. http://www.marinespecies.org/aphia.php?p=taxlist&tName=Gad%25%20Mor%25 

The downside will be tying ourselves into the WoRMS webservice remaining available.

**Comment by bthe** [comment]
Sounds reasonable, it may also be useful to be able to add a species regardless of the origin of the taxonomy. So in the case where I have a species with NODC number attached to it that is not in mfdb::species I could define these prior to the upload. 

Or would you just prefer to have a one-off list of species with NODC ids that are in our stomach data base and are not in mfdb::species. I expect that is needed only once.

**Comment by lentinj** [comment]
A one-off list seems easier for now. Then can discuss use of WoRMS in Romania.

**Comment by lentinj** [comment]
Example code:-
- https://github.com/einarhjorleifsson/fishvice/blob/master/R/WoRMS.R
- http://www.marinespecies.org/aphia.php?p=webservice&type=r
- https://github.com/ropensci/taxizesoap

**Comment by vbartolino** [comment]
In practice how can I add a new species to the species taxonomy list in mfdb?
There are at least 2-3 species which could be relevant to have in.
Thankful for any suggestion
\Valerio

**Comment by lentinj** [comment]
Send me a pull request to modify species.txt, or just paste in here what you want added.

**Comment by vbartolino** [comment]
"Saduria entomon" is probably the big missing from that list. This benthic invertebrate can make up to 20-30% of the cod stomach weight for certain cod length groups. There are of course other missing, but this is certainly the main one. Thanks for the addition

**Comment by lentinj** [comment]
@vbartolino Done - https://github.com/mareframe/mfdb/commit/152480d2fbfc39659bad612641a64c14b6406eeb

Reinstall MFDB and it'll add it to the database automatically.

**Comment by lentinj** [comment]
FWIW http://www.ices.dk/marine-data/Documents/RDB/RDB%20Exchange%20Format.pdf suggests a preference for WoRMS in ICES.

**Comment by lentinj** [comment]
6.x makes the species taxonomy modifiable, since long-term this is the only sensible thing to do.
