### ISSUE TITLE
stomach_preymeanweight problem with "zeros"

### ISSUE THREAD

**Issue by vbartolino** [mareframe/mfdb#31]
It seems that mfdb_stomach_preymeanweight() does not consider in the calculation of the mean those stomachs where a prey was not found (=zeros). Barbara and I think this could be a problem as the weight of a prey which occurs rarely in the stomachs but in high weight would be easily overestimated. This is likely the case for cod cannibalism.

From what I've been able to check (but I may be wrong) the number of entries in the prey table for a prey is used as denominator to calculate the mean weight of the prey in the somachs. I would see more appropriate to use the unique number of stomachs in 'stomach_name' from the predator table instead.

**Comment by lentinj** [comment]
`mfdb_stomach_preymeanweight` essentially ignores which stomach the sample was from and weights by count across all stomachs. So I think you've understood correctly.

Weighting by distinct stomachs would also produce a useful answer when count = `NA`, so I can definitely see the value of doing so in at least some situations. Generally, I'm getting the impression that stomach surveys don't turn up useful counts anyway. Which makes sense.

My main question I think is whether the current behaviour is useful at all, or both have their place?

**Comment by bbauer-su** [comment]
An answer from the EwE perspective: the only information I get from stomachs is diet composition, which is the average percentage of prey, by biomass, within the area and time period I'm interested in. Also, I often need prey items grouped (e.g. different flatfish species are summed up). For making the diet composition, I'm not particularly interested in individual behavior, but relative biomass flows across biomass pools. 
So, what I do now is to query the database in the most unaggregated way possible, then sum up prey weight in the desired groups from all stomachs found within the areas and period queried. Then I calculate the percentages from this. Taking the mean prey weights dividing by total number of stomachs (instead of prey count) as Valerio suggested and use these to calculate percentages would be mathematically equivalent I think. 
I can't think of a way at the moment how the current behavior of the function could be useful for me. For fish prey I need some information about their approximate age, but I get this from prey mean length, and not weight (especially because prey weights are not necessarily individual anyway). 
I hope this helps.

**Comment by vbartolino** [comment]
I share your same view, my impression is that the presence ratio and the stomach weight are much more useful information than the count

**Comment by lentinj** [comment]
Okay, so we should rewrite `mfdb_stomach_preymeanweight` to weight using the number of unique stomachs. That's easy enough. I've got some ideological concerns about changing the meaning of the function, but I don't think anyone else is using it and it saves me from thinking of a new name :)

This said, sounds like what is really required is another ratio function using biomass rather than simply presence / absence. Will let you know when I have something to try.

**Comment by lentinj** [comment]
Okay, sorry for the delay. I've now fixed `mfdb_stomach_preymeanweight` to work as we discussed.

I've also added a `mfdb_stomach_preyweightratio` to do the percentage calculation, but looking at the example EwE model I have here, this might not be as useful as multiple `mfdb_stomach_preymeanweight` calls, using `mfdb_concatenate_results` to combine them into one table. I will work out an example for this.

**Comment by bbauer-su** [comment]
'mfdb_stomach_preyweightratio' seems to work fine :)

I'm not sure what mfdb_stomach_preymeanweight does though. Are you sure you're dividing by the number of all stomachs queried? 
In my test, e.g. in 1982 cod as prey is only found once for cod predators length<35, with weight 12.75, in rectangle 39H0. When I query 1982 for SD 25-29 combined, again for cod predators length<35,  I get cod mean prey weight 12.75, although it has not been found in stomachs in any other rectangle, so it should be less. Also, if I calculate percentages from the mean weights myself I get quite different results than those with 'mfdb_stomach_preyweightratio'. 

About the EwE model,I'm not sure what you mean, but I only use percentages in the diet composition and no weights. So I'd only need the preyweightratio function. 

It could also be that my update of mfdb was not successful, but I get slightly different results from the mfdb_stomach_preymeanweight query than before, so I think I'm using the new version.

**Comment by lentinj** [comment]
> I'm not sure what mfdb_stomach_preymeanweight does though. Are you sure you're dividing by the number of all stomachs queried? 

Agh, you're right. It's only dividing by the stomachs where prey was present. That's no good. Will fix this later today.

**Comment by lentinj** [comment]
@bbauer-su Should be fixed!

**Comment by bbauer-su** [comment]
Looks good now!

**Comment by lentinj** [comment]
Excellent. Cheers!
