### ISSUE TITLE
Update to RPostgres?

### ISSUE THREAD

**Issue by bthe** [mareframe/mfdb#54]
Just out of curiosity, is it worthwhile to update the mfdb package from RPostgresSQL to the new RPostgres package (https://github.com/r-dbi/RPostgres).

**Comment by lentinj** [comment]
Worth a try. Last time I looked it sounded a bit beta, but that was a while a go.

I'll install it and re-run the tests, see what happens.

**Comment by lentinj** [comment]
Hrm, blindly switching them results in plenty of errors. But they don't look that serious.

**Comment by lentinj** [comment]
There's now a rpostgres-support branch where all the tests run again, with both DBI drivers. Transactions behave differently between the 2 DBI drivers, which picked up a lot of corner cases. It still uses ``RPostgreSQL`` by default. You can try by passing in ``db_params = list(drv = RPostgres::Postgres())`` to mfdb().

Haven't decided if it'd make more sense to switch entirely to RPostgres rather than trying to support both.

**Comment by lentinj** [comment]
(it doesn't actually need a schema change, just the sort of change that needs a major bump of version)

**Comment by lentinj** [comment]
In ``wip-7.x``, will be done when that's released.
